Implement proper logging HttpMiddleware
zio/zio-web pull request #87
Opened 2020-11-21 13:53 UTC by anovakovic01

This PR resolves #71.

2020-11-21 18:40 UTC, jdegoes commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +  def logging(dest: ZManaged[Blocking, IOException, OutputStream]): HttpMiddleware[Blocking with Clock, Exception] =
What I would do here is maybe accept a `Sink` that takes the input lines (`String`). Then have a default method that creates a sink that logs to a file (obviously have to think about log rotation and such but no need to do that now).

2020-11-22 11:31 UTC, anovakovic01 commented on core/src/test/scala/zio/web/HttpMiddlewareSpec.scala
> +            result <- l.request.processor(("GET", new URI("http://zio.dev")))
@jdegoes What is the easiest way to trigger middleware logic from test?

2020-11-22 11:32 UTC, anovakovic01 commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +        Response.none
I still need to somehow connect Response to the logging and add the response code and size.

2020-11-23 01:46 UTC, jdegoes commented
@anovakovic01 You need any more direction / help with this?

The other thing I would do is move this to `zio.web.http.middleware`.

Looking good!

2020-11-23 09:00 UTC, anovakovic01 commented
@jdegoes I'm almost done, just need to finish tests (that will be done as soon as `run` methods are merged to master). I appreciate your help on the issue. Thank you very much!

2020-12-01 06:52 UTC, pshemass commented
@jdegoes should this middleware use `zio-logging` or maybe this middleware should be in `zio-logging`?

2020-12-17 04:01 UTC, jdegoes commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +  def logging[R, E](sink: ZSink[R, E, String, Byte, Long]): HttpMiddleware[Clock with R, Nothing] = {
Let's move this logging middleware into `zio.web.http.middleware`, for organizational purposes.

2020-12-17 04:01 UTC, jdegoes commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +  def fileSink(path: String): ZSink[Blocking, Throwable, String, Byte, Long] = {
This looks like a helper, so we can keep it private.

2020-12-17 04:02 UTC, jdegoes commented on core/src/test/scala/zio/web/middleware/HttpMiddlewareSpec.scala
> +package zio.web.middleware
This should be `zio.web.http.middleware`.

2020-12-17 04:02 UTC, jdegoes requested changes
Just a few minor tweaks and then good to merge. Thanks for your work on this!

2020-12-17 08:16 UTC, anovakovic01 commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +  def fileSink(path: String): ZSink[Blocking, Throwable, String, Byte, Long] = {
If I make this private, the end users won't be able to create logging middleware that will write to the file. Should I create `fileLogging` middleware and then make this function private?

2020-12-19 05:09 UTC, jdegoes commented on core/src/main/scala/zio/web/http/HttpMiddleware.scala
> +  def fileSink(path: String): ZSink[Blocking, Throwable, String, Byte, Long] = {
Yes, that sounds like a good midway point. Thank you!

2021-01-01 19:46 UTC, jdegoes commented
@anovakovic01 Thank you. Excellent work!

2021-01-01 19:47 UTC, merged