#91: Create zio.web.http.openapi
zio/zio-web pull request #99
Opened 2020-11-22 10:18 UTC by saeltz

2020-11-22 10:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-web?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-web?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-web?pullRequest=99) it.</sub>

2020-11-22 16:52 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  // TODO: SpecificationExtensions (https://spec.openapis.org/oas/v3.0.3#specificationExtensions) that start with x- as Map[String, Any]
I'd remove the TODOs here, and instead, add them as Github issues.

2020-11-22 16:53 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require("^[a-zA-Z0-9.\\-_]+$.".r.matches(name))
This could cause a blowup here. I'd instead make a smart constructor in the companion object:

```scala
def fromString(...): Option[Key] = 
```

Then make `Key` private constructor:

```scala
sealed abstract case class Key private (name: String) {
}
```

That way, you can only create it from the smart constructor in the companion object.

2020-11-22 16:54 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  type Paths = Map[Path, PathItem]
May be worth making this a `final case class`.

2020-11-22 16:54 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require("^/[a-zA-Z0-9.\\-_]+$.".r.matches(name))
Ditto on smart constructor approach.

2020-11-22 16:55 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    servers: Seq[Server]
Instead of using `Seq`, always choose a concrete type, so that users know the performance guarantees they can expect:

1. `List` if the users will do head/tail pattern matching.
2. `Chunk` if the users will do random access and ZIO is already a dependency.
3. `Vector` if random access and ZIO is not a dependency.

2020-11-22 16:55 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +      case p: Parameter.QueryParameter if name == p.name && in == p.in => true
Is this a good definition of equality? I am not sure.

2020-11-22 16:56 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +        require((readOnly && !writeOnly) || (!readOnly && writeOnly) || (!readOnly && !writeOnly))
Ditto on smart constructor.

2020-11-22 16:57 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    style: String = "form",
Are there any constraints on this?

2020-11-22 16:57 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require((operationRef.isDefined && operationId.isEmpty) || (operationRef.isEmpty && operationRef.isDefined))
Ditto on smart constructor, but it should be defined on `operationRef` and `operationId`, not here.

2020-11-22 16:58 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +        require((readOnly && !writeOnly) || (!readOnly && writeOnly) || (!readOnly && !writeOnly))
Actually we could eliminate that by using a `sealed trait` for the read/write mode, which could be `ReadOnly` or `WriteOnly`. 

The model doesn't have to be 100% literal, it's probably more important to make it safe for consumption by Scala developers than to make it 100% literal.

2020-11-22 16:59 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  final case class SecurityRequirement(securitySchemes: Map[String, Seq[String]])
More use of `Seq`.

2020-11-22 16:59 UTC, jdegoes requested changes
Looks fantastic! Just a few minor polishing tips and will be good to merge.

2020-11-22 19:45 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +      case p: Parameter.QueryParameter if name == p.name && in == p.in => true
This is according to the spec: https://spec.openapis.org/oas/v3.0.3#parameter-object

> A unique parameter is defined by a combination of a name and location.

2020-11-22 21:16 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  // TODO: SpecificationExtensions (https://spec.openapis.org/oas/v3.0.3#specificationExtensions) that start with x- as Map[String, Any]
Done in https://github.com/zio/zio-web/pull/99/commits/1a9bab3765361b67ff743303310d4b7dbf2e8dd1 and created https://github.com/zio/zio-web/issues/101.

2020-11-22 21:16 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require("^[a-zA-Z0-9.\\-_]+$.".r.matches(name))
Done in https://github.com/zio/zio-web/pull/99/commits/c486c675aac69c34bfaed0e0b3f84a0c40cbc5b1.

2020-11-22 21:16 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  type Paths = Map[Path, PathItem]
Why would you do that?

2020-11-22 21:17 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require("^/[a-zA-Z0-9.\\-_]+$.".r.matches(name))
Done in https://github.com/zio/zio-web/pull/99/commits/c486c675aac69c34bfaed0e0b3f84a0c40cbc5b1.

2020-11-22 21:17 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  final case class SecurityRequirement(securitySchemes: Map[String, Seq[String]])
Done in https://github.com/zio/zio-web/pull/99/commits/e434b685cc63b624eef0d3346a072d4c450a404e.

2020-11-22 21:18 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    servers: Seq[Server]
Decided for `List` in https://github.com/zio/zio-web/pull/99/commits/e434b685cc63b624eef0d3346a072d4c450a404e because no dependency on ZIO yet and I don't see why someone would want random access.

2020-11-22 21:19 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    require((operationRef.isDefined && operationId.isEmpty) || (operationRef.isEmpty && operationRef.isDefined))
I removed `operationId` entirely in https://github.com/zio/zio-web/pull/99/commits/e8398218fd4fdd5d6e4ef9f70c15c76f5d302056 after reading that it's disregarded and `operationRef` should be used instead.

2020-11-22 21:19 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    style: String = "form",
Yes, added them in https://github.com/zio/zio-web/pull/99/commits/aa87f65be93a4ef8297837eef6d5651f23d7abab.

2020-11-22 21:20 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +        require((readOnly && !writeOnly) || (!readOnly && writeOnly) || (!readOnly && !writeOnly))
Using the approach of `sealed trait` in https://github.com/zio/zio-web/pull/99/commits/9b239327c04f197ef28988db91ba51c44ac7b6e4.
I named the two cases `RequestSchema` and `ResponseSchema` because depending on the `readOnly` or `writeOnly` they may be used only in requests or responses.

2020-11-22 21:21 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * @param email The email address of the contact person/organization. MUST be in the format of an email address. // TODO: is there an email type?
Do we have an email type or `RegExp` at hand?

2020-11-22 21:23 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call. // TODO: NonEmptyMap
Do we have a `NonEmptyMap` in ZIO or should I use something along the lines of `NonEmptyChunk[(StatusCode, ResponseOrReference)]` (loosing the guarantee of a keyset)?

2020-11-23 01:48 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call. // TODO: NonEmptyMap
For now I would use `Map`, but we can eventually make NonEmptyMap.

2020-11-23 01:51 UTC, jdegoes commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * @param email The email address of the contact person/organization. MUST be in the format of an email address. // TODO: is there an email type?
No, unfortunately. Maybe just use a String for now. Or you could do `case class Email` with a smart constructor and email regexp.

2020-11-24 07:08 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * @param email The email address of the contact person/organization. MUST be in the format of an email address. // TODO: is there an email type?
Using a `String` for now.

2020-11-24 07:10 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +   * The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call. // TODO: NonEmptyMap
Using a `Map` for now.

2020-11-24 07:11 UTC, saeltz commented
@jdegoes, I addressed your changes. Please re-review. Thanks for the feedback!

2020-11-26 03:42 UTC, igrebenik commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  )
Looks like **Info** has two required fields. They are "title" and "version" according to Spec. It turns out that "description" and "termsOdService" are optional as well.

2020-11-26 03:42 UTC, igrebenik commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  final case class Contact(name: Option[String], url: Option[URI], email: String)
The Spec doesn't force both "name" and "url" to optional. It deoesn't state that which field is optional and which is not. What if to make this a sum type instead of  a product? Like so:
```scala
sealed trait Contact 
object Contact {
  case class Name(name: String) extends Contact
  case calss URI(uri: java.net.URI) extends Contact
  case class Email(email: String) extends Contact
  case class Both(left: Contact, right: Contact) extends Contact
}
```
"Contact.Both" will allow to express any combination of fields. Well, naming might be bad though.
Don't know if it gets overcomplicated but at least it will work

2020-11-26 03:42 UTC, igrebenik commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    def in: String
String type is way too broad for "in" b\c it has only three values: "query", "header" and "cookie'. It should be enum.

2020-11-26 03:42 UTC, igrebenik commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  sealed trait Parameter extends ParameterOrReference {
I think you can get rid of "in" completely since it is reflected in terms of **Parameter**.
I would make Paramter as a product type because a lot fields get duplicated in every terms. They are:  
```scala
 name: String,
 description: Doc,
 deprecated: Boolean = false,
 allowEmptyValue: Boolean = false,
 definition: Definition,
  allowReserved: Boolean
  explode: Boolean = true,
  examples: Map[String, ExampleOrReference]
```
and have another field, say, ParameterType or something. This field will be a sum type and each term would define "in", "style" and so on. This appoach potentially might be a bit cleaner.

2020-11-29 17:40 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  )
I just copied this example from the issue created by John: https://github.com/zio/zio-web/issues/91
One could use an empty `Doc` (we could add that as default) and make `termsOfService` optional.
What do you think?

2020-11-29 17:57 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  final case class Contact(name: Option[String], url: Option[URI], email: String)
According to http://spec.openapis.org/oas/v3.0.3#fixed-fields-1 none of the fields are marked as required.
I agree though that it doesn't make sense to have an all empty `Contact` and if one wants to do that, they could still just not include `Contact` in the `Info` at all.

2020-11-29 17:59 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +    def in: String
It's not user-defined but already hard-coded in the respective subclasses of `Parameter`.
What would be the advantage of having that an ADT if it's only used in the output (to be implemented).

2020-11-29 18:00 UTC, saeltz commented on core/src/main/scala/zio/web/http/openapi/OpenAPI.scala
> +  sealed trait Parameter extends ParameterOrReference {
I tried that first and then stumbled upon different default values per `in` for `style` etc. That's why I chose this approach.

2020-12-17 04:27 UTC, jdegoes commented
@saeltz Thank you for your work on this! I will merge this as-is.

@igrebenik I like your idea to make this model a bit more precise with some enums. Would you be up for a followup PR?

2020-12-17 04:27 UTC, jdegoes approved these changes

2020-12-17 04:27 UTC, merged